version: '3'
services:
  racingcode:
    command: npm start
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/app
      - /var/app/node_modules
      - /var/app/coverage
      - /var/app/logs

  testing:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/app
      - /var/app/node_modules
      - /var/app/coverage
      - /var/app/logs
